module.exports = {
  BENCHES_RECEIVED: "BENCHES_RECEIVED",
  BENCH_RECEIVED: "BENCH_RECEIVED",

  BOUNDS_FILTER_RECEIVED: "BOUNDS_FILTER_RECEIVED",
  MIN_SEATS_FILTER_RECEIVED: "MIN_SEATS_FILTER_RECEIVED",
  MAX_SEATS_FILTER_RECEIVED: "MAX_SEATS_FILTER_RECEIVED",

  NEW_REVIEW_RECEIVED: "NEW_REVIEW_RECEIVED"
};
