module.exports = {
  BENCHES_RECEIVED: "BENCHES_RECEIVED",
  NEW_BENCH_RECEIVED: "NEW_BENCH_RECEIVED",
  BOUNDS_FILTER_RECEIVED: "BOUNDS_FILTER_RECEIVED",
  MIN_SEATS_FILTER_RECEIVED: "MIN_SEATS_FILTER_RECEIVED",
  MAX_SEATS_FILTER_RECEIVED: "MAX_SEATS_FILTER_RECEIVED"
};
